### ISSUE TITLE
Uncaught exception error

### ISSUE THREAD

**Issue by schwerg** [michbeck100/pimatic-hap#55] opened 2016-11-18 08:13 UTC
hap 0.9.0 on pimatic 0.9.36 sometimes gives:
```
error [pimatic]: A uncaught exception occured: Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)
 This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by schwerg** [comment] 2016-11-18 08:16
hap V0.9.0 on pimatic 0.9.36

**Comment by michbeck100** [comment] 2016-11-18 08:43
Duplicate of #30 and #10. Please see #10 for the solution. This error is not pimatic-hap related. My experience shows that it's something network related. Sometimes a reboot of your raspberry helps.

**Closed as completed by michbeck100** 2016-11-18 08:43 UTC
Labels: duplicate
