### ISSUE TITLE
Can't change color

### ISSUE THREAD

**Issue by Xento** [michbeck100/pimatic-hap#24] opened 2016-01-30 16:58 UTC
I can't change the color via siri.

I get the following error message:
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property '0' of undefined
    at convert.rgb.hex (/usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/color-convert/conversions.js:574:33)
    at /usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/color-convert/route.js:60:10
    at Object.wrappedFn [as hex](/usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/color-convert/index.js:39:16)
    at null.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-hap/accessories/ledlight.coffee:93:29)
    at EventEmitter.emit (events.js:106:17)
    at Characteristic.setValue (/usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/Characteristic.js:151:10)
    at Bridge.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/Accessory.js:537:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/Accessory.js:486:8)
    at HAPServer.EventEmitter.emit (events.js:106:17)
    at HAPServer._handleCharacteristics (/usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/HAPServer.js:696:10)
    at HAPServer.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/lib/HAPServer.js:178:39)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by michbeck100** [comment] 2016-01-31 18:38
Can you tell what the command was you were using?

**Comment by Xento** [comment] 2016-01-31 20:12
For example "set lamp to green". I tried different colors.

**Comment by michbeck100** [comment] 2016-02-02 07:17
@Xento What kind of led light device are you using?

**Comment by Xento** [comment] 2016-02-02 20:16
I'm using pimatic-led-light.
With my implementation of the saturation it worked.

**Comment by michbeck100** [comment] 2016-02-02 20:40
I mean what kind of device are you using with the pimatic-led-light plugin? Milight, blinkstick etc.
BTW: I did a rewrite of the color handling, so i just have a single dependency (color-convert). And i did test it with my hyperion installation at home, which worked flawless.

**Comment by michbeck100** [comment] 2016-02-02 20:45
The issue is probably inside one of the other device implementations, because i have absolutely no problem changing the color using the Hyperion or DummyLedLight device.

**Comment by michbeck100** [comment] 2016-02-02 20:56
And please make sure that you use the most recent version of pimatic-hap. Just delete it from node_modules and restart pimatic.

**Comment by michbeck100** [comment] 2016-02-10 19:49
@Xento Does this issue with the newest plugin version still exist?

**Comment by Xento** [comment] 2016-02-10 22:07
It is still there but I noticed, when I change the color once after a restart of pimatic everything works as expected.

**Comment by michbeck100** [comment] 2016-02-10 22:08
Ok, i'll close this issue for now. And will optimize the plugin.

**Closed as completed by michbeck100** 2016-02-10 22:08 UTC
Labels: bug
