### ISSUE TITLE
Shutter device always open

### ISSUE THREAD

**Issue by gine78** [michbeck100/pimatic-hap#40] opened 2016-09-12 10:30 UTC
Hello @michbeck100,

i have a IOS10 GM install and a shutter device. If i open the blind with pimatic - iOS tells me every Time "Jalousie geöffnet" (Blind OPEN).

I tink there is a error in the communication between Pimatic and hap/IOS.

How can i reproduce that, that u can work with it?
##

**Comment by michbeck100** [comment] 2016-09-12 10:37
The communication between pimatic and homekit is bidirectional. That means that if anything gets switched in pimatic, the state of homekit is refreshed, too. Since iOS sends a notification if blinds are opened, you got your issue. So i wouldn't say this is an error, but rather expected behavior. Or i misunderstand you.

**Comment by gine78** [comment] 2016-09-12 15:26
I try to repruduce this today in the afternoon. IOS thinks all times, that my blinds are open. Onbly if i toggle the blinds with ios, the status is correct.

**Comment by gine78** [comment] 2016-09-12 19:06
I think its a other error:

i close via Pimatic the blind. IOS screened "Jalousie close" in the Menu (ios 10) is the status "is closing..." (wird geschlossen). There becomes no update, that the blind is close. The status is pending by "is closing".

Is it possible to send a command by a rule after closing that the blind are close?

If i press "down" and press after a few seconds "Stop", the blind Stops - and ios screened "Jalousie wird geöffnet" (Is opening). I think its better if the stop Command are sending no command to hap?!

Es ist sehr schwer das auf englisch zu erklären. Ich schreib Dir auch gern eine PN wenn Du nicht weist was ich meine.
Its hard to explain in english, i can write a pn in German if you dont understand.

Thank you very much!

**Comment by michbeck100** [comment] 2016-09-12 19:38
I'll check this with the dummy shutter. I haven't really tested these in the wild, because I don't own automatic blinds

**Comment by michbeck100** [comment] 2016-09-12 19:40
Please try to install again using the command line from the pimatic-hap folder in node_modules. I'm not sure but it might be a temporary problem with the download source

**Comment by gine78** [comment] 2016-09-12 20:07
Whot? I just update to hap 0.8.0

**Comment by michbeck100** [comment] 2016-09-13 03:44
0.8.0 contains no changes regarding blinds.  
You'll have to wait for the next release.

**Comment by michbeck100** [comment] 2016-09-13 07:38
I checked the implementation but couldn't find anything wrong at the moment. Currently pimatic-hap is using the garage door opener functionality, because this is the closest to the shutter states that pimatic supports. So when pressing down from pimatic the value CLOSED is send to IOS. When pressing up it sends OPEN and for stop it sends STOPPED. There a no other states. Its actually quite simple.

**Comment by michbeck100** [comment] 2016-09-13 07:39
If you like to write a pm in german just use the pimatic forum plz.

**Comment by blacktiger333** [comment] 2016-09-29 18:35
any news about this issue? If "is opening" or "is closing" as status in homekit is shown, than I assume that a missing time value for opening / closing time might be a reason - or a special Message event could be required - but that's just an assumption - haven't check the ios 10 homekit api.

**Comment by michbeck100** [comment] 2016-11-02 21:26
Please check if the issue is still present. https://github.com/michbeck100/pimatic-hap/commit/a2da48ac67bebe6a40ad48d571b5c01ed3891c85 should fix the problem. If the problem isn't gone just reopen this issue.

**Closed as completed by michbeck100** 2016-11-02 21:26 UTC
