### ISSUE TITLE
dns service error

### ISSUE THREAD

**Issue by ikewestbrook** [michbeck100/pimatic-hap#30] opened 2016-03-26 21:20 UTC
Since today, the server logs show the following error:

error [pimatic]: A uncaught exception occured: Error: dns service error: unknown
    at Advertisement.on_service_registered (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)
 This is most probably a bug in pimatic or in a module, please report it!

Any Ideas?

**Comment by michbeck100** [comment] 2016-03-26 21:32
Duplicate of https://github.com/michbeck100/pimatic-hap/issues/10

**Closed as completed by michbeck100** 2016-03-26 21:32 UTC
Labels: duplicate, wontfix
