### ISSUE TITLE
Devices not accessible in iOS10 Home App

### ISSUE THREAD

**Issue by thymian** [michbeck100/pimatic-hap#36] opened 2016-06-15 09:49 UTC
Hey, I know its only 2 days out, but i want to inform you about an issue running pimatic-hap with iOS 10 dev beta 1 and the nativ "Home"-App.

Often when I open the Home app every switch and lamp says "no response" and cant be switched. I then have to go into the device details for some seconds and after that i can switch the device flawless.

For me (without any knowledge) it seems like the connection is shut down after some time without switching and only going into the device-prefs connects the devices again.

I recorded a video to show exactly what im talking about: https://youtu.be/u5vR5prcbYc

Strange thing: now 5 minutes after i recorded the video all devices are switchable again. This will change in some minutes (or even hours?) 
Heres a screenshot of the app when devices are accessible:
<img src="https://cloud.githubusercontent.com/assets/10746167/16075277/8c60470e-32ee-11e6-84d1-bb8953c61760.PNG" width="200">

pimatic-hap v. 0.6.3
pimatic v. 0.9.18
iPhone 6S iOS10

**Comment by michbeck100** [comment] 2016-06-15 10:09
Anything in the debug log?

**Comment by thymian** [comment] 2016-06-15 12:19
sorry i‘ve to ask, but how can i turn hap debug on? pimatic-daemon.log only got 
`12:15:44.591 [pimatic-hap] Starting homekit bridge`

**Comment by michbeck100** [comment] 2016-06-15 12:40
set debug to true and logLevel to "debug" in settings tag (see https://pimatic.org/pages/config/)

**Comment by thymian** [comment] 2016-06-15 14:41
Thanks for the reply. I uploaded my log because i cant see anything strange inside it
[pimatic-daemon.txt](https://github.com/michbeck100/pimatic-hap/files/316331/pimatic-daemon.txt)

**Comment by michbeck100** [comment] 2016-06-15 14:47
I don't see anything strange either. Because the problem just exists on iOS 10 i would like to defer this issue. If there is an issue, it is very likely that it has to do with the HomeKit library that is used in pimatic-hap (https://github.com/KhaosT/HAP-NodeJS). As of now there are no issues like yours there. But i would to wait a little if there will be a new release for iOS 10.

**Comment by michbeck100** [comment] 2016-06-16 13:31
I got another question: Do you have the same behavior with one of the other homekit apps like Legato's Eve? If not, i would say its a problem of the new app.

**Comment by thymian** [comment] 2016-06-17 07:24
i wouldn't say its a problem of the new app, because Eve cant reach devices, too. 

<img src="https://cloud.githubusercontent.com/assets/10746167/16143018/6156c1f0-346a-11e6-90ab-756cc7f9afb6.PNG" width="200">
⚠️💬 in english: "Device locked atm. Try again"

i reset everything now and added them again. lets see how long that works

**Comment by michbeck100** [comment] 2016-08-17 08:55
Could you test if the issue is still there with the newest beta of iOS 10?

**Comment by thymian** [comment] 2016-08-23 13:55
will try this in a couple of days

**Comment by michbeck100** [comment] 2016-09-09 19:18
I installed the Golden Master of IOS 10 and right from the start i had no problems using the home app with pimatic-hap. I close this issue therefore.

**Closed as completed by michbeck100** 2016-09-09 19:18 UTC
