### ISSUE TITLE
Does not work 100% on iOS 11

### ISSUE THREAD

**Issue by 0xFelix** [michbeck100/pimatic-hap#76] opened 2017-10-14 17:51 UTC
I set up a new and fresh instance of pimatic and installed pimatic-hap. After that I configured some switches and sensors and paired pimatic-hap to an iOS 11 device. All switches and sensors can be seen/read/switched, but on all devices a "!" is shown and the Home app says the device does not respond. Despite the warnings everything works and switches can be toggled etc.. I tested the same setup on an iOS 10 device, everything works there and no "!" are shown. What could be the problem?

**Comment by michbeck100** [comment] 2017-10-14 19:09
I‘ve seen the same behavior on my iOS 11 devices, both iPhone and iPad. But after a while of doing nothing about it, it’s gone and everything works without problems.

**Comment by 1janwillem** [comment] 2017-10-23 09:30
Hi,

I am experiencing the same problem, after the install of iOS 11 all was still working, but after the recently released new version of pimatic-hap all the switches/thermostats offered through pimatic-hap give an exclamation mark in the Home app in iOS11. They do work, both ways.

**Comment by wrmulf** [comment] 2017-10-23 14:31
I can confirm, that the issues appeared with the latest update from v0.10.0 to v0.11.0.

**Comment by michbeck100** [comment] 2017-10-25 11:07
Could you please comment which plugins you use, that are supported by pimatic-hap. I have the feeling that the problem is related to a single plugin. I will test this by disabling one device after another and check if it gets better. The "!" problem seems to occur for all devices if just one device is not answering properly.
Otherwise you can always go back to the last version using this tutorial: https://forum.pimatic.org/topic/1114/updated-how-to-install-a-plugin-from-github-using-npm-or-git

**Comment by wrmulf** [comment] 2017-10-25 11:58
I use two instances of pimatic on two different rasbperry pis (one is called pi, the other one rb). Both are added to the same HomeKit-Account.  Devices of both pimatic instances are rendered unreachable.

pi uses amazing-dash-button, hue-zll, shell-execute and rflink.
rb uses amazing-dash-button, hue-zll, shell-execute, homeduino and led-light.

Both pimatic instances have echo and hap enabled.

**Comment by michbeck100** [comment] 2017-10-25 13:26
Should be fixed now. The problem was that with KhaosT/HAP-NodeJS@445b340 setting Service.BridgingState was removed from hap-nodejs (as of version 0.4.26).

**Comment by michbeck100** [comment] 2017-10-25 13:30
Fix was released with 0.11.1

**Closed as completed** 2017-10-25 13:30 UTC

**Comment by 0xFelix** [comment] 2017-10-25 17:34
Works fine now!

**Comment by 1janwillem** [comment] 2017-10-25 18:08
Works indeed! Thx for the fix!
